# precios_oferta_query = '''
# SELECT
#     DISTINCT
#     INICIO,
#     FIN,
#     ORIN,
#     ESTADISTICO,
#     MIN(PROM_PVP_OFERTA) AS MIN_PROM_PVP_OFERTA,
#     PROM_PVP_OFERTA,
#     FIN_AJUSTADO,
#     EVENTO_DESC,
#     ARTC_ARTC_DESC
# FROM
#     (
#     SELECT
#         DISTINCT
#         FP.PROM_FECHA_INICIO AS INICIO,
#         FP.PROM_FECHA_FIN AS FIN,
#         LAA.ORIN,
#         LAA.ARTC_ARTC_COD AS ESTADISTICO,
#         FP.PROM_PVP_OFERTA,
#         FIN + 30 AS FIN_AJUSTADO,
#         LPE.EVENTO_DESC,
#         LAA.ARTC_ARTC_DESC
#     FROM
#         MSTRDB.DWH.FT_PROMOS AS FP
#         INNER JOIN MSTRDB.DWH.LU_PROM_EVENTO AS LPE ON LPE.EVENTO_ID = FP.EVENTO_ID
#
#         INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FP.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
#     WHERE
#         FP.PROM_FECHA_FIN >= DATEADD(DAY, -10, CURRENT_DATE)
#     ORDER BY
#         3 DESC)
# GROUP BY
#     ALL
# '''

precios_oferta_query = '''
SELECT
    DISTINCT
    INICIO,
    FIN,
    ORIN,
    ESTADISTICO,
    MIN(PROM_PVP_OFERTA) AS MIN_PROM_PVP_OFERTA,
    median(PROM_PVP_OFERTA) PROM_PVP_OFERTA,
    FIN_AJUSTADO,
    EVENTO_DESC,
    ARTC_ARTC_DESC
FROM
    (
    SELECT
        DISTINCT        
        FP.PROM_FECHA_INICIO AS INICIO,
        FP.PROM_FECHA_FIN AS FIN,
        LAA.ORIN,
        LAA.ARTC_ARTC_COD AS ESTADISTICO,
        FP.PROM_PVP_OFERTA,
        FIN + 30 AS FIN_AJUSTADO,
        LPE.EVENTO_DESC,
        LAA.ARTC_ARTC_DESC
    FROM
        MSTRDB.DWH.FT_PROMOS AS FP
        INNER JOIN MSTRDB.DWH.LU_PROM_EVENTO AS LPE ON LPE.EVENTO_ID = FP.EVENTO_ID

        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FP.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
    WHERE
        FP.PROM_FECHA_FIN >= DATEADD(DAY, -90, CURRENT_DATE)
        and lpe.tipo_oferta_id in (4,25,11,12,24)
    ORDER BY
        3 DESC) 
GROUP BY
    ALL
'''

precios_stock_mediano_query = '''
    SELECT
        DISTINCT
        LPTO.*,
        FP.PROM_FECHA_INICIO AS INICIO,
        FP.PROM_FECHA_FIN AS FIN,
        --LAA.ARTC_ARTC_ID,
        --LAA.ARTC_ARTC_COD,
        --LAA.ARTC_ARTC_DESC,
        LAA.ORIN,
        MEDIAN(FS.STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_STOCK_MEDIANO
    FROM
        MSTRDB.DWH.FT_PROMOS AS FP
        INNER JOIN MSTRDB.DWH.LU_PROM_EVENTO AS LPE ON LPE.EVENTO_ID = FP.EVENTO_ID
        INNER JOIN MSTRDB.DWH.LU_PROM_TIPO_OFERTA AS LPTO ON LPTO.TIPO_OFERTA_ID = LPE.TIPO_OFERTA_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FP.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.FT_STOCK AS FS ON FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID AND FS.TIEM_DIA_ID = CURRENT_DATE - 1
    GROUP BY
        ALL
'''

opt_query = '''
SELECT
    --LAA.ARTC_ARTC_ID,
    --LAA.ARTC_ARTC_COD,
    --LAA.ARTC_ARTC_DESC,
    LAA.ORIN,
    ROUND(MEDIAN(OPT.PRECIO_COMPETENCIA), 1) AS AVG_PRECIO_COMPETENCIA
FROM
    SPIKE.SPIKE.BASE_OPT AS OPT
    INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON OPT.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON OPT.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
--WHERE
    --COMP_COMP_ID IN ('RETAIL', 'COMPETENCIA')
GROUP BY
    ALL
'''

locales_activos_ayer_query = '''
SELECT
    --LAA.ARTC_ARTC_DESC AS ARTICULO,
    LAA.ORIN,
    --LAA.ARTC_ARTC_ID,
    COUNT(DISTINCT FS.GEOG_LOCL_ID) AS LOCALES_ACTIVOS_AYER
FROM
    MSTRDB.DWH.FT_STOCK AS FS
    LEFT JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
WHERE
    ARTC_ESTA_ID = 4
    AND LAA.ORIN IS NOT NULL
    AND GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)
    AND GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_LOCL_COD IN (101,102,103,104,107,108,111,115,117,119,120,121,122,124,125,126,127,131,132,134,139,140,141,143,144,145,146,147,148,149,150,151,152,153,155,156,157,158,159,160,161,162,163,164,165,167,166,168,173,198,301,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335))
    AND FS.TIEM_DIA_ID = CURRENT_DATE() - 1
GROUP BY
    ALL
HAVING
    LOCALES_ACTIVOS_AYER > 0
'''

days_on_hand_articulo_query = '''
WITH ARTICULOS_TATA AS
    (
    SELECT
        DISTINCT LAA.ORIN
    FROM
        MSTRDB.DWH.DIVISION AS DIVISION
        INNER JOIN MSTRDB.DWH.GROUPS AS GROUPS ON DIVISION.DIVISION = GROUPS.DIVISION
        INNER JOIN MSTRDB.DWH.DEPS AS DEPS ON DEPS.GROUP_NO = GROUPS.GROUP_NO
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.DEPT = DEPS.DEPT
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON LAA.ORIN = IM.ITEM
    WHERE
        DIVISION.DIV_NAME ILIKE '%TATA%'
    ),

STOCK AS
    (
    SELECT
        IM.SUBCLASE,
        LAA.ARTC_ARTC_DESC,
        LAA.ORIN,
        LAA.ARTC_ARTC_ID,
        SUM(FS.STCK_UNIDADES) AS UNIDADES
    FROM
        MSTRDB.DWH.FT_STOCK AS FS
        LEFT JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON LAA.ORIN = IM.ITEM
    WHERE
        FS.TIEM_DIA_ID = CURRENT_DATE() - 1
        AND GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_LOCL_COD IN (101,102,103,104,107,108,111,115,117,119,120,121,122,124,125,126,127,131,132,134,139,140,141,143,144,145,146,147,148,149,150,151,152,153,155,156,157,158,159,160,161,162,163,164,165,167,166,168,173,198,301,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335))
  
    GROUP BY
        ALL
    ),

VENTAS AS
    (
    SELECT
        FV.ARTC_ARTC_ID,
        (SUM(FV.VNTA_UNIDADES) / 30) AS UNIDADES_VENDIDAS
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
    WHERE
        FV.TIEM_DIA_ID >= DATEADD(DAYS, -29, CURRENT_DATE()-1)
        AND GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_LOCL_COD IN (101,102,103,104,107,108,111,115,117,119,120,121,122,124,125,126,127,131,132,134,139,140,141,143,144,145,146,147,148,149,150,151,152,153,155,156,157,158,159,160,161,162,163,164,165,167,166,168,173,198,301,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335))
  
    GROUP BY
        ALL
    )

SELECT
    STOCK.*,
    COALESCE(VENTAS.UNIDADES_VENDIDAS, 0) AS UNIDADES_VENDIDAS
FROM
    STOCK
    LEFT JOIN VENTAS ON VENTAS.ARTC_ARTC_ID = STOCK.ARTC_ARTC_ID
WHERE
    STOCK.ORIN IN (SELECT * FROM ARTICULOS_TATA)
'''

days_on_hand_subclase_query = '''
WITH ARTICULOS_TATA AS
    (
    SELECT
        DISTINCT IM.SUBCLASE
    FROM
        MSTRDB.DWH.DIVISION AS DIVISION
        INNER JOIN MSTRDB.DWH.GROUPS AS GROUPS ON DIVISION.DIVISION = GROUPS.DIVISION
        INNER JOIN MSTRDB.DWH.DEPS AS DEPS ON DEPS.GROUP_NO = GROUPS.GROUP_NO
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.DEPT = DEPS.DEPT
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON LAA.ORIN = IM.ITEM
    WHERE
        DIVISION.DIV_NAME ILIKE '%TATA%'
    ),

STOCK AS
    (
    SELECT
        SUB.SUBCLASE,
        SUB.SUB_NAME,
        SUM(FS.STCK_UNIDADES) AS UNIDADES
    FROM
        MSTRDB.DWH.FT_STOCK AS FS
        LEFT JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
        INNER JOIN MSTRDB.DWH.SUBCLASS AS SUB ON SUB.SUBCLASE = IM.SUBCLASE

    WHERE
        FS.TIEM_DIA_ID = CURRENT_DATE() - 1
        AND GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_LOCL_COD IN (101,102,103,104,107,108,111,115,117,119,120,121,122,124,125,126,127,131,132,134,139,140,141,143,144,145,146,147,148,149,150,151,152,153,155,156,157,158,159,160,161,162,163,164,165,167,166,168,173,198,301,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335))
  
    GROUP BY
        ALL
    ),

VENTAS AS
    (
    SELECT
        SUB.SUBCLASE,
        (SUM(FV.VNTA_UNIDADES) / 30) AS UNIDADES_VENDIDAS
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
        INNER JOIN MSTRDB.DWH.SUBCLASS AS SUB ON SUB.SUBCLASE = IM.SUBCLASE
    WHERE
        FV.TIEM_DIA_ID >= DATEADD(MONTH, -1, CURRENT_DATE()-1)
        AND GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_LOCL_COD IN (101,102,103,104,107,108,111,115,117,119,120,121,122,124,125,126,127,131,132,134,139,140,141,143,144,145,146,147,148,149,150,151,152,153,155,156,157,158,159,160,161,162,163,164,165,167,166,168,173,198,301,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335))
  
    GROUP BY
        ALL
    )

SELECT
    STOCK.*,
    COALESCE(VENTAS.UNIDADES_VENDIDAS, 0) AS UNIDADES_VENDIDAS
FROM
    STOCK
    LEFT JOIN VENTAS ON VENTAS.SUBCLASE = STOCK.SUBCLASE
WHERE
    STOCK.SUBCLASE IN (SELECT * FROM ARTICULOS_TATA)
'''

top_5_query = '''
WITH MINIMO_30_TICKETS AS
    (
    SELECT
        LAA.ORIN,
        COUNT(DISTINCT FV.TICKET) AS TICKETS
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FV.TIEM_DIA_ID >= DATEADD(MONTH, -1, CURRENT_DATE)
    GROUP BY
        ALL
    HAVING
        TICKETS > 30
    )

SELECT
    IM.SUBCLASE,
    LAA.ORIN,
    LAA.ARTC_ARTC_DESC,
    FV.TICKET,
    SUM(FV.VNTA_IMPORTE_SIN_IVA) - SUM(FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND) AS GB1
FROM
    MSTRDB.DWH.FT_VENTAS AS FV
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
    INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
    INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
WHERE
    LGL.GEOG_UNNG_ID = 2
    AND FV.TIEM_DIA_ID >= DATEADD(MONTH, -1, CURRENT_DATE)
    AND LAA.ORIN IN (SELECT ORIN FROM MINIMO_30_TICKETS)
GROUP BY
    ALL
'''

unidades_regulares_query = '''
WITH MINIMO_30_TICKETS AS
    (
    SELECT
        LAA.ORIN,
        COUNT(DISTINCT FV.TICKET) AS TICKETS
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FV.TIEM_DIA_ID >= DATEADD(MONTH, -1, CURRENT_DATE)
    GROUP BY
        ALL
    HAVING
        TICKETS > 30
    )

SELECT
    LAA.ORIN,
    LAA.ARTC_ARTC_DESC,
    FV.TICKET,
    FV.TIEM_DIA_ID,
    SUM(FV.VNTA_UNIDADES) AS UNIDADES
FROM
    MSTRDB.DWH.FT_VENTAS AS FV
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
    INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
WHERE
    LGL.GEOG_UNNG_ID = 2
    AND FV.TIEM_DIA_ID >= DATEADD(MONTH, -1, CURRENT_DATE)
    AND LAA.ORIN IN (SELECT ORIN FROM MINIMO_30_TICKETS)
GROUP BY
    ALL
'''

unidades_promo_query_1 = '''
WITH ARTICULOS_TATA AS
    (
    SELECT
        DISTINCT LAA.ORIN
    FROM
        MSTRDB.DWH.DIVISION AS DIVISION
        INNER JOIN MSTRDB.DWH.GROUPS AS GROUPS ON DIVISION.DIVISION = GROUPS.DIVISION
        INNER JOIN MSTRDB.DWH.DEPS AS DEPS ON DEPS.GROUP_NO = GROUPS.GROUP_NO
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.DEPT = DEPS.DEPT
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON LAA.ORIN = IM.ITEM
    WHERE
        DIVISION.DIV_NAME ILIKE '%TATA%'
    ),

FECHA_UNICA AS
    (
    SELECT
        EVENTO_ID,
        COUNT(DISTINCT PROM_FECHA_INICIO) AS INICIOS,
        COUNT(DISTINCT PROM_FECHA_FIN) AS FINES
    FROM
        MSTRDB.DWH.FT_PROMOS
    GROUP BY
        ALL
    HAVING
        INICIOS = 1
        AND FINES = 1
    ),

EXCLUIMOS_PROMOS_1 AS
    (
    SELECT
        DISTINCT EVENTO_ID
    FROM
        MSTRDB.DWH.LU_PROM_EVENTO LPR 
    WHERE
        EVENTO_DESC ILIKE '%LIQUIDACI%N%'
    ),
    
EXCLUIMOS_PROMOS_2 AS
    (
    SELECT
        DISTINCT EVENTO_ID
    FROM
        MSTRDB.DWH.FT_PROMOS
    WHERE
        PROM_FECHA_INICIO >= CURRENT_DATE
    ),

PROMOS AS
    (
    SELECT
        DISTINCT
        FP.EVENTO_ID,
        LAA.ORIN,
        LAA.ARTC_ARTC_DESC,
        FP.ARTC_ARTC_ID,
        FP.PROM_FECHA_INICIO,
        FP.PROM_FECHA_FIN
    FROM
        MSTRDB.DWH.FT_PROMOS AS FP
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FP.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
    WHERE
        FP.EVENTO_ID IN (SELECT EVENTO_ID FROM FECHA_UNICA)
        AND FP.EVENTO_ID NOT IN (SELECT * FROM EXCLUIMOS_PROMOS_1)
        AND FP.EVENTO_ID NOT IN (SELECT * FROM EXCLUIMOS_PROMOS_2)
        AND FP.PROM_FECHA_INICIO >= DATEADD(YEAR, -1, CURRENT_DATE)
        AND LAA.ORIN IN (SELECT * FROM ARTICULOS_TATA)
    ORDER BY
        FP.PROM_FECHA_FIN DESC
    )

SELECT * FROM PROMOS
'''

unidades_promo_query_2 = '''
WITH ARTICULOS_TATA AS
    (
    SELECT
        DISTINCT LAA.ORIN
    FROM
        MSTRDB.DWH.DIVISION AS DIVISION
        INNER JOIN MSTRDB.DWH.GROUPS AS GROUPS ON DIVISION.DIVISION = GROUPS.DIVISION
        INNER JOIN MSTRDB.DWH.DEPS AS DEPS ON DEPS.GROUP_NO = GROUPS.GROUP_NO
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.DEPT = DEPS.DEPT
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON LAA.ORIN = IM.ITEM
    WHERE
        DIVISION.DIV_NAME ILIKE '%TATA%'
    )

SELECT
    FV.TIEM_DIA_ID,
    LAA.ORIN,
    SUM(FV.VNTA_UNIDADES) AS UNIDADES
FROM
    MSTRDB.DWH.FT_VENTAS AS FV
    INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
WHERE
    FV.TIEM_DIA_ID >= DATEADD(YEAR, -1, CURRENT_DATE)
    AND LAA.ORIN IN (SELECT * FROM ARTICULOS_TATA)
GROUP BY
    ALL
ORDER BY
    1,
    2
'''

ft_stock_ayer_query = '''
WITH ARTICULOS_EN_ACTIVIDAD AS
    (
    SELECT
        DISTINCT LAA.ORIN
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FV.TIEM_DIA_ID >= DATEADD(MONTH, -3, CURRENT_DATE)
    )
    
    SELECT
        LAA.ORIN,
        LAA.ARTC_ARTC_DESC,
        SUM(FS.STCK_UNIDADES) AS UNIDADES,
        MEDIAN(FS.STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_VENTA_DIA_MEDIANO
    FROM
        MSTRDB.DWH.FT_STOCK AS FS
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FS.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
    WHERE
        (LGL.GEOG_UNNG_ID = 2 OR LGL.GEOG_LOCL_COD = 100)
        AND FS.TIEM_DIA_ID = CURRENT_DATE - 1
        AND LAA.ORIN IN (SELECT ORIN FROM ARTICULOS_EN_ACTIVIDAD)
    GROUP BY
        ALL
'''

pack_size = '''
WITH ARTICULOS_EN_ACTIVIDAD AS
    (
    SELECT
        DISTINCT LAA.ORIN
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FV.TIEM_DIA_ID >= DATEADD(MONTH, -3, CURRENT_DATE)
        AND LAA.ORIN NOT ILIKE '-1'
    )

SELECT
    LAA.ORIN,
    LAA.ARTC_INNER_PACK_SIZE
FROM
    MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA
WHERE
    LAA.ORIN IN (SELECT ORIN FROM ARTICULOS_EN_ACTIVIDAD)
'''

reporte_articulos = '''
SELECT
    DISTINCT
    FP.EVENTO_ID,
    FP.PROM_FECHA_INICIO,
    FP.PROM_FECHA_FIN,
    LGL.GEOG_LOCL_COD,
    LGL.GEOG_LOCL_DESC,
    LAA.ORIN,
    LAA.ARTC_ARTC_COD,
    LAA.ARTC_ARTC_DESC
FROM
    MSTRDB.DWH.FT_PROMOS AS FP
    INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FP.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FP.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
WHERE
    FP.PROM_FECHA_INICIO > CURRENT_DATE
    AND LAA.ORIN NOT ILIKE '-1'
'''

aceleracion = '''
SELECT * FROM mstrdb.plus.venta_promo_orin
'''