SELECT
    '0' AS ZONE_NODE_TYPE, NULL AS ZONE_GROUP_ID, NULL AS ZONE_ID, GEOG_LOCL_COD AS LOCATION, ORIN AS ITEM, NULL AS DIFF_ID, NULL AS SKULIST,
    NULL AS LINK_CODE, '2' AS CHANGE_TYPE, PRECIO_NUEVO_AJUSTADO AS CHANGE_AMOUNT, NULL AS CHANGE_PERCENT, 'EA' AS CHANGE_SELLING_UOM,
    NULL AS PRICE_GUIDE_ID, EFFECTIVE_DATE, '2' AS REASON_CODE, '0' AS VENDOR_FUNDED_IND, NULL AS FUNDING_TYPE, NULL AS FUNDING_AMOUNT,
    NULL AS FUNDING_AMOUNT_CURRENCY, NULL AS FUNDING_PERCENT, NULL AS DEAL_ID, NULL AS DEAL_DETAIL_ID
FROM
    SANDBOX_PLUS.DWH.RECOPILACION_MODIFICACIONES_PRECIOS_BIS 
WHERE 
    FECHA_ANALISIS = CURRENT_DATE AND TABLA={cond};