WITH PP AS (
SELECT
    DISTINCT A.CODIGO_TIENDA, B.FAMILIA, COUNT(DISTINCT A.PVP_NUEVO) AS P
FROM
    SANDBOX_PLUS.DWH.INPUT_PRICING_ACUMULADO A
LEFT JOIN
    SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B
ON
    A.ORIN = B.ORIN AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD
WHERE
    FECHA_EJECUCION = (SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS)
AND
    TABLA={cond}
GROUP BY ALL
)

SELECT
    A.*, B.FAMILIA, B.ARTC_ARTC_DESC, B.STCK_PRECIO_VENTA_DIA_CIVA
FROM
    SANDBOX_PLUS.DWH.INPUT_PRICING_ACUMULADO A
JOIN
    SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B
ON
    A.ORIN = B.ORIN AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD
JOIN
    PP
ON
    A.CODIGO_TIENDA = PP.CODIGO_TIENDA AND B.FAMILIA = PP.FAMILIA AND P>1
WHERE
    FECHA_EJECUCION=(SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS)
AND
    TABLA={cond}
ORDER BY
    GEOG_LOCL_COD, B.FAMILIA;