SELECT
    GROUP_NAME AS GRUPO, DEPT_NAME AS DEPTO, CLASS_NAME AS CLASE, SUB_NAME AS SUBCLASE, A.ITEM, B.ITEM_DESC AS DESCRIPCION, FAMILIA
FROM
    SANDBOX_PLUS.DWH.RELACIONES_ITEM_PARENT_ACTUALIZADOS A
JOIN
    MSTRDB.DWH.ITEM_MASTER B ON A.ITEM::TEXT = B.ITEM::TEXT AND ITEM_NUMBER_TYPE = 'ITEM'
JOIN
    MSTRDB.DWH.DEPS C ON C.DEPT = B.DEPT
JOIN
    MSTRDB.DWH.GROUPS D ON D.GROUP_NO = C.GROUP_NO
JOIN
    MSTRDB.DWH.CLASS E ON E.CLASE = B.CLASE
JOIN
    MSTRDB.DWH.SUBCLASS F ON F.SUBCLASE = B.SUBCLASE
WHERE
    A.ITEM IS NOT NULL;