SELECT
    ORIN, GEOG_LOCL_COD AS CODIGO_TIENDA, PRECIO_NUEVO_AJUSTADO AS PVP_NUEVO
FROM
    SANDBOX_PLUS.DWH.RECOPILACION_MODIFICACIONES_PRECIOS_BIS
WHERE 
    FECHA_ANALISIS = CURRENT_DATE AND TABLA={cond};