WITH P AS (
SELECT
    ARTC_ARTC_ID, MEDIAN(STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_MEDIANO,
    ROUND(AVG(STCK_PRECIO_VENTA_DIA_CIVA), 2) AS PRECIO_PROMEDIO
FROM
    MSTRDB.DWH.FT_STOCK
WHERE
    TIEM_DIA_ID = {cond2}
GROUP BY ALL
)

, STOCK AS (
SELECT
    DISTINCT FS.ARTC_ARTC_ID, FS.GEOG_LOCL_ID, FS.STCK_UNIDADES, FS.STCK_PRECIO_VENTA_DIA_CIVA AS PVP_ACTUAL,
    FCUR.UNIT_COST AS COSTO_UNITARIO, FCUR.ORIGIN_COUNTRY_ID AS MONEDA_COSTO,
    COSTO_UNITARIO * ROUND(FS.STCK_PRECIO_VENTA_DIA_CIVA/FS.STCK_PRECIO_VENTA_DIA, 2) AS COSTO_UNITARIO_CON_IVA
FROM
    MSTRDB.DWH.FT_STOCK FS
LEFT JOIN
    MSTRDB.DWH.FT_COSTO_UNITARIO_RMS FCUR
ON
    FS.GEOG_LOCL_ID = FCUR.GEOG_LOCL_ID AND FS.ARTC_ARTC_ID = FCUR.ARTC_ARTC_ID
    AND FCUR.TIEM_DIA_ID = FS.TIEM_DIA_ID
WHERE
    FS.TIEM_DIA_ID = {cond2}
)

SELECT
    LGL.GEOG_LOCL_COD AS LOCAL, LAA.ORIN, LAA.ARTC_ARTC_DESC, PVP_ACTUAL, PRECIO_MEDIANO, PRECIO_PROMEDIO,
    CASE WHEN IL.LOC IS NOT NULL AND DD.GROUP_NO IS NOT NULL THEN 'USD' ELSE 'UYU' END AS MONEDA_PRECIO,
    COSTO_UNITARIO_CON_IVA, MONEDA_COSTO,
    ROUND(DIV0(PVP_ACTUAL - COSTO_UNITARIO_CON_IVA, PVP_ACTUAL), 2) AS MARGEN, STCK_UNIDADES
FROM
    STOCK AS FS
JOIN
    MSTRDB.DWH.LU_ARTC_ARTICULO LAA
ON
    FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
JOIN
    MSTRDB.DWH.ITEM_MASTER IM
ON
    IM.ITEM = LAA.ORIN AND IM.ITEM_NUMBER_TYPE = 'ITEM'
LEFT JOIN
    MSTRDB.DWH.DEPS DD
ON
    DD.DEPT = IM.DEPT AND DD.GROUP_NO = 25
JOIN
    MSTRDB.DWH.LU_GEOG_LOCAL LGL
ON
    FS.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
JOIN
    P
ON
    FS.ARTC_ARTC_ID = P.ARTC_ARTC_ID
LEFT JOIN
    MSTRDB.DWH.ITEM_LOC IL
ON
    IL.ITEM = LAA.ORIN AND IL.LOC/100 = LGL.GEOG_LOCL_COD AND IL.TIEM_DIA_ID = {cond2}
    AND IL.UNIT_RETAIL BETWEEN PVP_ACTUAL - 1 AND PVP_ACTUAL + 1
{cond};