WITH A AS (
SELECT
    DISTINCT TO_DATE(FCPR.FECHA_SOLICITUD) AS FECHA_SOLICITUD, S.SUPPLIER, FCPR.GEOG_LOCL_COD, LAA.ORIN, LAA.ARTC_ARTC_DESC,
    ROUND(MEDIAN(FCUR.COSTO_UNITARIO_RMS), 2) AS COSTO_ACTUAL, FCPR.COSTO_SIN_IVA AS COSTO_NUEVO,
    ROUND(DIV0(COSTO_NUEVO - COSTO_ACTUAL, COSTO_ACTUAL), 2) AS INCREMENTO, FCPR.PVP_SUGERIDO, FCPR.NRO_SOLICITUD AS LISTA
FROM
    MSTRDB.DWH.LU_ARTC_ARTICULO LAA
JOIN
    MSTRDB.DWH.LU_ARTC_CODIGO_BARRAS LACB
ON LAA.ARTC_ARTC_ID = LACB.ARTC_ARTC_ID
JOIN
    MSTRDBDESA.DWH.FT_COSTO_PROVEEDOR_RESULTADO FCPR
ON LACB.ARTC_COBA_COD = FCPR.ITEM AND FCPR.GEOG_LOCL_COD IS NOT NULL AND
    FCPR.NRO_SOLICITUD IN (SELECT NRO_SOLICITUD FROM MSTRDBDESA.DWH.FT_COSTO_PROVEEDOR_RESULTADO WHERE ESTADO = 'Aceptado')
JOIN
    MSTRDB.DWH.SUPS S
ON S.SUP_NAME_SECONDARY = FCPR.RUT_PROVEEDOR AND S.SUPPLIER_PARENT IS NULL AND S.SUP_NAME_SECONDARY IS NOT NULL
JOIN
    MSTRDB.DWH.LU_GEOG_LOCAL LGL
ON LGL.GEOG_LOCL_COD = FCPR.GEOG_LOCL_COD
JOIN
    MSTRDB.DWH.FT_COSTO_UNITARIO_RMS FCUR
ON FCUR.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID AND LGL.GEOG_LOCL_ID = FCUR.GEOG_LOCL_ID AND FCUR.TIEM_DIA_ID = CURRENT_DATE() - 1
GROUP BY ALL
)

, B AS (
SELECT
    DISTINCT TO_DATE(FCPR.FECHA_SOLICITUD) AS FECHA_SOLICITUD, S.SUPPLIER, FCPR.GEOG_LOCL_COD, LAA.ORIN, LAA.ARTC_ARTC_DESC,
    ROUND(MEDIAN(FCUR.COSTO_UNITARIO_RMS), 2) AS COSTO_ACTUAL, FCPR.COSTO_SIN_IVA AS COSTO_NUEVO,
    ROUND(DIV0(COSTO_NUEVO - COSTO_ACTUAL, COSTO_ACTUAL), 2) AS INCREMENTO, FCPR.PVP_SUGERIDO, FCPR.NRO_SOLICITUD AS LISTA
FROM
    MSTRDB.DWH.LU_ARTC_ARTICULO LAA
JOIN
    MSTRDB.DWH.LU_ARTC_CODIGO_BARRAS LACB
ON LAA.ARTC_ARTC_ID = LACB.ARTC_ARTC_ID
JOIN
    MSTRDBDESA.DWH.FT_COSTO_PROVEEDOR_RESULTADO FCPR
ON LACB.ARTC_COBA_COD = FCPR.ITEM AND FCPR.GEOG_LOCL_COD IS NULL AND
    FCPR.NRO_SOLICITUD IN (SELECT NRO_SOLICITUD FROM MSTRDBDESA.DWH.FT_COSTO_PROVEEDOR_RESULTADO WHERE ESTADO = 'Aceptado')
JOIN
    MSTRDB.DWH.SUPS S
ON S.SUP_NAME_SECONDARY = FCPR.RUT_PROVEEDOR AND S.SUPPLIER_PARENT IS NULL AND S.SUP_NAME_SECONDARY IS NOT NULL
JOIN
    MSTRDB.DWH.FT_COSTO_UNITARIO_RMS FCUR
ON FCUR.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID AND FCUR.TIEM_DIA_ID = CURRENT_DATE() - 1
GROUP BY ALL
) 
SELECT *, NULL AS ESTADO FROM A UNION ALL SELECT *, NULL AS ESTADO FROM B;