WITH ART AS (
SELECT
    G.GROUP_NO, G.GROUP_NAME AS GRUPO, D.DEPT AS D_ID, D.DEPT_NAME AS DEPT, C.CLASE AS C_ID, C.CLASS_NAME AS CLASE, S.SUBCLASE AS S_ID, S.SUB_NAME AS SUBCLASE,
    IM.ITEM, LAA.ARTC_ARTC_ID, LAA.ARTC_ARTC_DESC
FROM
    MSTRDB.DWH.ITEM_MASTER IM
JOIN
    MSTRDB.DWH.DEPS D
ON
    D.DEPT = IM.DEPT AND D.DEPT <> 3
JOIN
    MSTRDB.DWH.GROUPS G
ON
    D.GROUP_NO = G.GROUP_NO AND G.GROUP_NO IN (1, 3, 4, 11, 12, 14, 15, 18)
JOIN
    MSTRDB.DWH.CLASS C
ON
    IM.CLASE = C.CLASE AND C.CLASE <> -1
JOIN
    MSTRDB.DWH.SUBCLASS S
ON
    IM.SUBCLASE = S.SUBCLASE AND S.SUBCLASE <> -1
JOIN
    MSTRDB.DWH.LU_ARTC_ARTICULO LAA
ON
    LAA.ORIN = IM.ITEM
WHERE
    IM.ITEM_NUMBER_TYPE = 'ITEM'
)

, DIM AS (
SELECT
    DISTINCT ITEM, LENGTH AS PROFUNDIDAD, WIDTH AS FRENTE, HEIGHT AS ALTURA, FLOOR(130/WIDTH) AS ITEMS_POR_FRENTE,
    CASE WHEN FLOOR(30/PROFUNDIDAD) = 0 THEN 1 ELSE FLOOR(30/PROFUNDIDAD) END AS ITEMS_POR_LATERAL, ITEMS_POR_LATERAL * ITEMS_POR_FRENTE AS CANT_MAX_X_ESTANTE,
    CASE WHEN ITEMS_POR_LATERAL > 2 THEN 2 * ITEMS_POR_FRENTE ELSE CANT_MAX_X_ESTANTE END AS CANT_MIN_X_ESTANTE
FROM
    SANDBOX_PLUS.DWH.V_ITEM_SUPP_COUNTRY_DIM
WHERE
    DIM_OBJECT='EA'
AND
    LWH_UOM='CM'
)

, P AS (
SELECT
    DISTINCT C.GEOG_LOCL_ID, C.GEOG_LOCL_COD, C.GEOG_LOCL_DESC, A.PUNTERA, A.SECCION, A.ITEM,
    A.FECHA_INICIO, A.FECHA_FIN, DATEDIFF('DAY', A.FECHA_INICIO, A.FECHA_FIN) + 1 AS DURACION_PUNTERA
FROM
    SANDBOX_PLUS.DWH.INPUT_PUNTERAS A
JOIN
    MSTRDB.DWH.LU_GEOG_LOCAL C
ON
    C.GEOG_LOCL_COD = A.LOCAL
WHERE
    UPPER(PUNTERA) NOT LIKE '%EX%BI%'
AND
    SECCION<>'NF'
)

, BASAL AS (
SELECT
    TIEM_DIA_ID, ARTC_ARTC_ID, GEOG_LOCL_ID, ROUND(AVG(VENTA_BASAL), 2) AS AVG_BASAL_180, ROUND(AVG(VENTA_REAL), 2) AS AVG_REAL_180 
FROM
    BIZMETRIKS.DWH.FT_VENTA_BASAL
WHERE
    TIEM_DIA_ID BETWEEN DATEADD('MONTH', -6, DATE_TRUNC('MONTH', CURRENT_DATE())) AND DATE_TRUNC('MONTH', CURRENT_DATE()+30) - 1
GROUP BY ALL
)

, V AS (
SELECT
    FV.TIEM_DIA_ID, FV.GEOG_LOCL_ID, FV.ARTC_ARTC_ID, SUM(FV.VNTA_IMPORTE_CON_IVA) AS VENTA, SUM(FV.VNTA_UNIDADES) AS UNIDADES
FROM
    MSTRDB.DWH.FT_VENTAS FV
WHERE
    TIEM_DIA_ID BETWEEN DATEADD('MONTH', -6, DATE_TRUNC('MONTH', CURRENT_DATE())) AND DATE_TRUNC('MONTH', CURRENT_DATE()) - 1
GROUP BY ALL
)

, VP AS (
SELECT
    P.FECHA_INICIO, P.FECHA_FIN, V.GEOG_LOCL_ID, P.GEOG_LOCL_COD, P.GEOG_LOCL_DESC, P.PUNTERA, P.SECCION, P.DURACION_PUNTERA, ART.*,
    ROUND(SUM(AVG_BASAL_180)/P.DURACION_PUNTERA, 2) AS AVG_BASAL_180, ROUND(SUM(V.UNIDADES)/P.DURACION_PUNTERA, 2) AS UNIDADES_PROMEDIO
FROM
    V
JOIN
    ART
ON
    ART.ARTC_ARTC_ID = V.ARTC_ARTC_ID
JOIN
    P
ON
    P.ITEM = ART.ITEM AND P.GEOG_LOCL_ID = V.GEOG_LOCL_ID AND V.TIEM_DIA_ID BETWEEN P.FECHA_INICIO AND P.FECHA_FIN
JOIN
    BASAL
ON
    BASAL.ARTC_ARTC_ID = V.ARTC_ARTC_ID AND BASAL.GEOG_LOCL_ID = V.GEOG_LOCL_ID AND V.TIEM_DIA_ID = BASAL.TIEM_DIA_ID
GROUP BY ALL
)

, AC AS (
SELECT
    *, ROUND(DIV0(UNIDADES_PROMEDIO, AVG_BASAL_180), 2) AS ACELERACION_ART, ROUND(MEDIAN(ACELERACION_ART) OVER (PARTITION BY ITEM), 2) AS ACELERACION_ART_GLOBAL,
    ROUND(MEDIAN(ACELERACION_ART) OVER (PARTITION BY S_ID, GEOG_LOCL_ID), 2) AS ACELERACION_SUBCLASE,
    ROUND(MEDIAN(ACELERACION_ART) OVER (PARTITION BY S_ID), 2) AS ACELERACION_SUBCLASE_GLOBAL,
    ROUND(MEDIAN(ACELERACION_ART) OVER (PARTITION BY C_ID, GEOG_LOCL_ID), 2) AS ACELERACION_CLASE,
    ROUND(MEDIAN(ACELERACION_ART) OVER (PARTITION BY C_ID), 2) AS ACELERACION_CLASE_GLOBAL
FROM
    VP
)

, CAB AS (
SELECT
    P.FECHA_INICIO, P.FECHA_FIN, P.GEOG_LOCL_ID, P.GEOG_LOCL_COD, P.GEOG_LOCL_DESC, P.PUNTERA, P.SECCION, P.DURACION_PUNTERA, ART.*,
    DIM.CANT_MAX_X_ESTANTE, DIM.CANT_MIN_X_ESTANTE, ROUND(AVG(BASAL.AVG_BASAL_180), 2) AS VENTA_BASAL,
    ACELERACION_ART, ACELERACION_ART_GLOBAL, ACELERACION_SUBCLASE, ACELERACION_SUBCLASE_GLOBAL, ACELERACION_CLASE, ACELERACION_CLASE_GLOBAL,

    CASE WHEN ACELERACION_ART IS NOT NULL AND ACELERACION_ART > 0 THEN ACELERACION_ART
        WHEN ACELERACION_ART_GLOBAL IS NOT NULL AND ACELERACION_ART_GLOBAL > 0 THEN ACELERACION_ART_GLOBAL
        WHEN ACELERACION_SUBCLASE IS NOT NULL AND ACELERACION_SUBCLASE > 0 THEN ACELERACION_SUBCLASE
        WHEN ACELERACION_SUBCLASE_GLOBAL IS NOT NULL AND ACELERACION_SUBCLASE_GLOBAL > 0 THEN ACELERACION_SUBCLASE_GLOBAL
        WHEN ACELERACION_CLASE IS NOT NULL AND ACELERACION_CLASE > 0 THEN ACELERACION_CLASE
        WHEN ACELERACION_CLASE_GLOBAL IS NOT NULL AND ACELERACION_CLASE_GLOBAL > 0 THEN ACELERACION_CLASE_GLOBAL
        ELSE 1 END AS ACELERACION,
    
    ROUND(VENTA_BASAL*ACELERACION, 2) AS VENTA_ACELERADA_DIARIA, VENTA_ACELERADA_DIARIA * DURACION_PUNTERA AS CARGA_SUGERIDA_X_VENTA,
    CASE WHEN VENTA_ACELERADA_DIARIA > 0 THEN ROUND(CANT_MAX_X_ESTANTE/VENTA_ACELERADA_DIARIA, 2) ELSE 1000 END AS DOH_CARGA_MAX,
    CASE WHEN VENTA_ACELERADA_DIARIA > 0 THEN ROUND(CANT_MIN_X_ESTANTE/VENTA_ACELERADA_DIARIA, 2) ELSE 1000 END AS DOH_CARGA_MIN
FROM
    ART
JOIN
    DIM ON DIM.ITEM = ART.ITEM
JOIN
    P ON P.ITEM = ART.ITEM AND P.FECHA_INICIO = {cond}
LEFT JOIN
    BASAL
ON
    BASAL.GEOG_LOCL_ID = P.GEOG_LOCL_ID AND BASAL.ARTC_ARTC_ID = ART.ARTC_ARTC_ID
LEFT JOIN
    (SELECT GEOG_LOCL_ID, ARTC_ARTC_ID, ROUND(AVG(ACELERACION_ART), 2) AS ACELERACION_ART FROM AC GROUP BY ALL) AA
ON
    AA.GEOG_LOCL_ID = P.GEOG_LOCL_ID AND AA.ARTC_ARTC_ID = ART.ARTC_ARTC_ID
LEFT JOIN
    (SELECT ARTC_ARTC_ID, ROUND(AVG(ACELERACION_ART_GLOBAL), 2) AS ACELERACION_ART_GLOBAL FROM AC GROUP BY ALL) AAG
ON
    AAG.ARTC_ARTC_ID = ART.ARTC_ARTC_ID
LEFT JOIN
    (SELECT GEOG_LOCL_ID, S_ID, ROUND(AVG(ACELERACION_SUBCLASE), 2) AS ACELERACION_SUBCLASE FROM AC GROUP BY ALL) ACS
ON
    ACS.GEOG_LOCL_ID = P.GEOG_LOCL_ID AND ACS.S_ID = ART.S_ID
LEFT JOIN
    (SELECT S_ID, ROUND(AVG(ACELERACION_SUBCLASE_GLOBAL), 2) AS ACELERACION_SUBCLASE_GLOBAL FROM AC GROUP BY ALL) ASG
ON
    ASG.S_ID = ART.S_ID
LEFT JOIN
    (SELECT GEOG_LOCL_ID, C_ID, ROUND(AVG(ACELERACION_CLASE), 2) AS ACELERACION_CLASE FROM AC GROUP BY ALL) ACC
ON
    ACC.GEOG_LOCL_ID = P.GEOG_LOCL_ID AND ACC.C_ID = ART.C_ID
LEFT JOIN
    (SELECT C_ID, ROUND(AVG(ACELERACION_CLASE_GLOBAL), 2) AS ACELERACION_CLASE_GLOBAL FROM AC GROUP BY ALL) ACG
ON
    ACG.C_ID = ART.C_ID
GROUP BY ALL
)

SELECT
    FECHA_INICIO, FECHA_FIN, GEOG_LOCL_ID, GEOG_LOCL_COD, GEOG_LOCL_DESC, SECCION, PUNTERA, DURACION_PUNTERA, GRUPO, DEPT, CLASE, SUBCLASE, ITEM, ARTC_ARTC_DESC,
    CANT_MAX_X_ESTANTE, CANT_MIN_X_ESTANTE, VENTA_BASAL, ACELERACION, VENTA_ACELERADA_DIARIA, CARGA_SUGERIDA_X_VENTA, DOH_CARGA_MAX, DOH_CARGA_MIN
FROM
    CAB
ORDER BY
    GEOG_LOCL_COD, SECCION, PUNTERA, DOH_CARGA_MAX;