WITH LIMPIO AS (
SELECT
    DISTINCT TABLA, EFFECTIVE_DATE, CODIGO_TIENDA, FAMILIA, PVP_NUEVO
FROM (
    SELECT
        DISTINCT TABLA, CODIGO_TIENDA, A.EFFECTIVE_DATE, A.ORIN, B.FAMILIA, PVP_NUEVO,
        ROW_NUMBER() OVER (PARTITION BY GEOG_LOCL_COD, B.FAMILIA ORDER BY A.PVP_NUEVO) AS RN_PRECIO
    FROM
        SANDBOX_PLUS.DWH.INPUT_PRICING_ACUMULADO A
    LEFT JOIN
        SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B
    ON
        A.ORIN = B.ORIN AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD
    WHERE
        FECHA_EJECUCION = (SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS)
    AND
        TABLA = {cond}
    QUALIFY
        RN_PRECIO = 1
    ORDER BY 1,3,2
    )
)

SELECT
    DISTINCT B.ORIN, B.GEOG_LOCL_COD, A.PVP_NUEVO, NULL AS EFFECTIVE_DATE, B.FAMILIA, B.INTEGRANTES_FAMILIA,
    B.CANASTA, B.ARTC_ARTC_DESC, ARTC_ESTA_ID AS ESTADO, ESTA_EN_PROMO, EXCLUIDO_COMERCIAL,
    CASE WHEN S.STCK_PRECIO_VENTA_DIA_CIVA <> A.PVP_NUEVO THEN 1 ELSE 0 END AS PRECIO_DIFERENTE
FROM
    SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B
JOIN
    LIMPIO A
ON
    A.FAMILIA = B.FAMILIA AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD
JOIN
    MSTRDB.DWH.FT_STOCK S
ON
    S.ARTC_ARTC_ID = B.ARTC_ARTC_ID AND S.GEOG_LOCL_ID = B.GEOG_LOCL_ID AND S.TIEM_DIA_ID = CURRENT_DATE - 1
WHERE
    FECHA_EJECUCION = (SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS);