# Usa Python ligero
FROM python:3.11-slim

# Directorio de la app
WORKDIR /app

# Copia requirements e instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos TODO el código de tu proyecto excepto que esté ignorado por el dockerignore 
COPY . .

# Exponemos el puerto de Streamlit
EXPOSE 8501

# Comando por defecto
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]