WITH P AS (
SELECT
    ARTC_ARTC_ID, MEDIAN(STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_MEDIANO
FROM
    MSTRDB.DWH.FT_STOCK
WHERE
    TIEM_DIA_ID = CURRENT_DATE - 1
GROUP BY ALL
)

, STOCK AS (
SELECT
    DISTINCT FS.ARTC_ARTC_ID, FS.GEOG_LOCL_ID, FS.STCK_PRECIO_VENTA_DIA_CIVA AS PVP_ACTUAL,
    CASE
        WHEN FCUR.ORIGIN_COUNTRY_ID = 'UYU' THEN FCUR.COSTO_UNITARIO_RMS
        ELSE FS.STCK_COSTO_PROM_POND
    END AS COSTO_UNITARIO,
    COSTO_UNITARIO * ROUND(FS.STCK_PRECIO_VENTA_DIA_CIVA/FS.STCK_PRECIO_VENTA_DIA, 2) AS COSTO_UNITARIO_CON_IVA
FROM
    MSTRDB.DWH.FT_STOCK FS
LEFT JOIN
    MSTRDB.DWH.FT_COSTO_UNITARIO_RMS FCUR
ON
    FS.GEOG_LOCL_ID = FCUR.GEOG_LOCL_ID AND FS.ARTC_ARTC_ID = FCUR.ARTC_ARTC_ID
    AND FCUR.TIEM_DIA_ID = (SELECT MAX(TIEM_DIA_ID) FROM MSTRDB.DWH.FT_COSTO_UNITARIO_RMS)
WHERE
    FS.TIEM_DIA_ID = CURRENT_DATE - 1
)

SELECT
    LAA.ORIN, LGL.GEOG_LOCL_COD AS LOCAL, PVP_ACTUAL, PRECIO_MEDIANO, COSTO_UNITARIO_CON_IVA,
    ROUND(DIV0(PVP_ACTUAL - COSTO_UNITARIO_CON_IVA, PVP_ACTUAL), 2) AS MARGEN
FROM
    STOCK AS FS
JOIN
    MSTRDB.DWH.LU_ARTC_ARTICULO LAA
ON
    FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
JOIN
    MSTRDB.DWH.LU_GEOG_LOCAL LGL
ON
    FS.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
JOIN
    P
ON
    FS.ARTC_ARTC_ID = P.ARTC_ARTC_ID;