WITH P AS (
SELECT ARTC_ARTC_ID, GEOG_LOCL_ID, MEDIAN(STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_MEDIANO
FROM MSTRDB.DWH.FT_STOCK WHERE TIEM_DIA_ID = CURRENT_DATE - 30 GROUP BY ALL
)

SELECT
    DISTINCT LAA.ORIN, LGL.GEOG_LOCL_COD AS LOCAL, FS.STCK_PRECIO_VENTA_DIA_CIVA AS PVP_ACTUAL, PRECIO_MEDIANO,
    FS.STCK_UNIT_COST * ROUND(FS.STCK_PRECIO_VENTA_DIA_CIVA/FS.STCK_PRECIO_VENTA_DIA, 2) AS COSTO_UNITARIO_CON_IVA
FROM MSTRDB.DWH.FT_STOCK FS
JOIN MSTRDB.DWH.LU_ARTC_ARTICULO LAA ON  FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID 
JOIN MSTRDB.DWH.LU_GEOG_LOCAL LGL ON FS.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
JOIN P ON FS.ARTC_ARTC_ID = P.ARTC_ARTC_ID AND FS.GEOG_LOCL_ID = P.GEOG_LOCL_ID
WHERE FS.TIEM_DIA_ID = CURRENT_DATE - 1;