WITH I_D AS (
SELECT
    ARTC_ARTC_ID, ROUND(DIV0(STCK_PRECIO_VENTA_DIA_CIVA, STCK_PRECIO_VENTA_DIA), 2) AS IVA,
    MEDIAN(STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_ACTUAL_MEDIANO_PARA_ARTICULOS_INACTIVOS_DISCONTINUADOS
FROM
    MSTRDB.DWH.FT_STOCK
WHERE
    TIEM_DIA_ID = {cond2}
AND
    ARTC_ESTA_ID <> 4
GROUP BY ALL
)

, A AS (
SELECT
    ARTC_ARTC_ID, ROUND(DIV0(STCK_PRECIO_VENTA_DIA_CIVA, STCK_PRECIO_VENTA_DIA), 2) AS IVA,
    MEDIAN(STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_ACTUAL_MEDIANO_PARA_ARTICULOS_ACTIVOS
FROM
    MSTRDB.DWH.FT_STOCK
WHERE
    TIEM_DIA_ID = {cond2}
AND
    ARTC_ESTA_ID = 4
GROUP BY ALL
)

SELECT
    LAA.ORIN, ROUND(MEDIAN(FS.COSTO_UNITARIO_RMS) * (MEDIAN(COALESCE(A.IVA, I_D.IVA)) + 1)) AS COSTO_UNITARIO_CON_IVA,
    A.PRECIO_ACTUAL_MEDIANO_PARA_ARTICULOS_ACTIVOS, I_D.PRECIO_ACTUAL_MEDIANO_PARA_ARTICULOS_INACTIVOS_DISCONTINUADOS
FROM
    MSTRDB.DWH.FT_COSTO_UNITARIO_RMS FS
JOIN
    MSTRDB.DWH.LU_ARTC_ARTICULO LAA
ON
    LAA.ARTC_ARTC_ID = FS.ARTC_ARTC_ID
LEFT JOIN
    A
ON
    LAA.ARTC_ARTC_ID = A.ARTC_ARTC_ID
LEFT JOIN
    I_D
ON
    LAA.ARTC_ARTC_ID = I_D.ARTC_ARTC_ID
WHERE
    FS.TIEM_DIA_ID = {cond2}
{cond}
GROUP BY ALL;